services:
  tdl_python_docker:
    image: liuxcserver/tdl_python_docker:latest
    container_name: tdl_python_docker
    volumes:
      - /vol1/1000/space/docker/tdl_python_docker/config:/root/.tdl # 保持配置持久化
      - /vol1/1000/space/docker/tdl_python_docker/download:/source_path
      - /vol02/1001-1-900c4d77/STRM/TDL:/target_path
    ports:
      - "18888:8888"
    network_mode: bridge
    restart: unless-stopped
    environment:
      - TDL_PROXY=socks5://tdl:123456@localhost:1080
      - TDL_THREADS=8    # 同时下载的任务数量
      - TDL_LIMIT=4      # 单个任务的下载线程数
      - TDL_POOL=30      # 客户端连接池信息
      - SECRET_KEY=123456   # 任务开启密码
      - START_TASK=True		# 上传任务是否开启
      - SOURCE_PATH=/source_path #本地下载目录
      - TARGET_PATH=/target_path #远端上传目录